# Generated by Django 6.0.2 on 2026-03-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_webcamcapture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcamcapture',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_captures', to='core.attempt'),
        ),
    ]
