# Generated by Django 6.0.2 on 2026-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_question_code_solution_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='code_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
