# Generated by Django 6.0.2 on 2026-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_question_sample_input_question_sample_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='temp_field',
            field=models.BooleanField(default=False),
        ),
    ]
