# Generated by Django 6.0.2 on 2026-03-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_question_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='temp_field',
        ),
    ]
