# Generated by Django 6.0.2 on 2026-03-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_question_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
