# Generated by Django 6.0.2 on 2026-03-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_answer_is_correct_alter_answer_selected_option'),
        ('core', '0028_question_blueprint'),
    ]

    operations = [
    ]
