# Generated by Django 6.0.2 on 2026-03-27 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20260327_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_type',
            field=models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='BlueprintSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('time_limit_minutes', models.PositiveIntegerField(default=15)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.testblueprint')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('blueprint', 'section_type', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('time_limit_minutes', models.PositiveIntegerField(default=15)),
                ('blueprint_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sections', to='core.blueprintsection')),
                ('questions', models.ManyToManyField(blank=True, related_name='test_sections', through='core.TestQuestion', to='core.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.test')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='core.section'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_questions', to='core.section'),
        ),
        migrations.CreateModel(
            name='AttemptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='core.attempt')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.section')),
            ],
            options={
                'ordering': ['section__order', 'id'],
                'unique_together': {('attempt', 'section')},
            },
        ),
    ]
