# Generated by Django 6.0.2 on 2026-03-30 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_question_section_type_blueprintsection_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_evaluation', to='core.answer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerAssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.CharField(blank=True, default='Medium', max_length=20)),
                ('total_duration_minutes', models.PositiveIntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_templates', to='core.testblueprint')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='core.testblueprint')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_test_assignments', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_assignments', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_assignments', to='core.employerassessmenttemplate')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.test')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployerAssessmentTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('time_limit_minutes', models.PositiveIntegerField(default=15)),
                ('blueprint_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_sections', to='core.blueprintsection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.employerassessmenttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'order')},
            },
        ),
    ]
