# Generated by Django 6.0.2 on 2026-04-07 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_codingevaluation_employerassessmenttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintrule',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.blueprintsection'),
        ),
    ]
