# Generated by Django 6.0.2 on 2026-04-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_blueprintrule_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsection',
            name='section_type',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('aptitude', 'Aptitude')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employerassessmenttemplatesection',
            name='section_type',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('aptitude', 'Aptitude')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='section_type',
            field=models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('aptitude', 'Aptitude')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('numerical', 'Numerical'), ('logical', 'Logical'), ('coding', 'Coding'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('aptitude', 'Aptitude')], max_length=20),
        ),
    ]
