# Generated by Django 6.0.2 on 2026-05-01 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_blueprintsection_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testassignment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.test'),
        ),
    ]
